
name: "fio-benchmark"

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      size:
        description: 'file size to read/write by fio'
        required: true
        default: '1G'
      nrfiles:
        description: 'number of files to read/write by fio'
        required: true
        default: 10000
jobs:
  big-file-sequential-read-github:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build linux target
        run: |
          make juicefs
      - name: start minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=minioadmin" \
                     -e "MINIO_SECRET_KEY=minioadmin" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data
      - name: Test 
        uses: ./.github/actions/fio
        with:
          meta_url: redis://localhost/1
          storage: minio
          bucket: http://localhost:9000/fio-test
          access_key: minioadmin
          secret_key: minioadmin
          fio_job: "big-file-sequential-read:  --rw=read --refill_buffers --bs=256k --size=${{ github.event.inputs.size }}"
          
      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1    
  # big-file-sequential-read:
  #   if: github.repository == 'juicedata/juicefs'
  #   runs-on: [self-hosted, daily-build, bench-01]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #     - name: Build linux target
  #       run: |
  #         export GOPATH=/usr/local/go
  #         export HOME=/root
  #         make juicefs
  #     - name: Test 
  #       uses: ./.github/actions/fio
  #       with:
  #         meta_url: redis://mymaster,172.27.0.1,172.27.0.2,172.27.0.3:26379/6
  #         storage: minio
  #         bucket: http://172.27.0.2:9005/fio-test
  #         access_key: minioadmin
  #         secret_key: ${{ secrets.MINIO_SECRET_KEY }}
  #         fio_job: "big-file-sequential-read:  --rw=read --refill_buffers --bs=256k --size=${size}"