name: "fio-benchmark"

on:
  push:
    branches: 
      - release-**
  pull_request:
    #The branches below must be a subset of the branches above
    branches: 
      - release-**
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      size:
        description: 'file size to read/write by fio'
        required: true
        default: '1G'
      nrfiles:
        description: 'number of files to read/write by fio'
        required: true
        default: 10000
jobs:
  big-file-sequential-read:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-sequential-read:  --rw=read --refill_buffers --bs=256k --size=${{ github.event.inputs.size }}"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-sequential-write:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-sequential-write:  --rw=write --refill_buffers --bs=256k  --size=${{ github.event.inputs.size }}"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-multi-read-1:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-multi-read-1:  --rw=read --refill_buffers --bs=256k --size=${{ github.event.inputs.size }} --numjobs=1"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-multi-read-4:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-multi-read-4:  --rw=read --refill_buffers --bs=256k --size=${{ github.event.inputs.size }} --numjobs=4"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-multi-read-16:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-multi-read-16:  --rw=read --refill_buffers --bs=256k --size=${{ github.event.inputs.size }} --numjobs=16"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-multi-write-1:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-multi-write-1:       --rw=write --refill_buffers --bs=256k --size=${{ github.event.inputs.size }} --numjobs=1"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-multi-write-4:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-multi-write-4:       --rw=write --refill_buffers --bs=256k --size=${{ github.event.inputs.size }} --numjobs=4"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-multi-write-16:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-multi-write-16:       --rw=write --refill_buffers --bs=256k --size=${{ github.event.inputs.size }} --numjobs=16"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-rand-read-4k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-rand-read-4k:       --rw=randread --refill_buffers --size=${{ github.event.inputs.size }} --filename=randread.bin --bs=4k" 
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}
      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1
        
  big-file-rand-read-256k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-rand-read-256k:       --rw=randread --refill_buffers --size=${{ github.event.inputs.size }} --filename=randread.bin --bs=256k" 
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}
      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1

  big-file-random-write-4k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-random-write-4k:    --rw=randwrite --refill_buffers --size=${{ github.event.inputs.size }} --bs=4k"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  big-file-random-write-256k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "big-file-random-write-256k:    --rw=randwrite --refill_buffers --size=${{ github.event.inputs.size }} --bs=256k"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-seq-read-4k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-seq-read-4k:      --rw=read --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} :--cache-size=0"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-seq-read-256k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-seq-read-256k:      --rw=read --file_service_type=sequential --bs=256k --filesize=256k --nrfiles=${{ github.event.inputs.nrfiles }} :--cache-size=0"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-seq-write-4k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-seq-write-4k:     --rw=write --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} :--writeback"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-seq-write-256k:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-seq-write-256k:     --rw=write --file_service_type=sequential --bs=256k --filesize=256k --nrfiles=${{ github.event.inputs.nrfiles }} :--writeback"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-multi-read-1:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-multi-read-1:      --rw=read --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} --numjobs=1"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-multi-read-4:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-multi-read-4:      --rw=read --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} --numjobs=4"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-multi-read-16:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-multi-read-16:      --rw=read --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} --numjobs=16"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-multi-write-1:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-multi-write-1:     --rw=write --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} --numjobs=1"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-multi-write-4:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-multi-write-4:     --rw=write --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} --numjobs=4"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}

  small-file-multi-write-16:
    if: github.repository == 'juicedata/juicefs'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test 
        uses: ./.github/actions/fio
        with:
          fio_job: "small-file-multi-write-16:     --rw=write --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=${{ github.event.inputs.nrfiles }} --numjobs=16"
          mysql_password: ${{secrets.MYSQL_PASSWORD_FOR_JUICEDATA}}
          PYROSCOPE_AUTH_TOKEN: ${{secrets.PYROSCOPE_AUTH_TOKEN}}





          