name: "mdtest"

on:
  workflow_dispatch:
    inputs:
      dirs:
        description: 'width for each directory'
        required: true
        default: 10
      depth:
        description: 'depth of all directories'
        required: true
        default: 3
      files:
        description: 'number of files for each directory'
        required: true
        default: 10
      threads:
        description: 'number of threads'
        required: true
        default: 10
      bytes:
        description: 'bytes of each file'
        required: true
        default: 8192

jobs:
  test-with-redis:
    runs-on: [self-hosted, daily-build, bench-01]
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/mdtest
        with:
          meta_url: "redis://mymaster,172.27.0.1,172.27.0.2,172.27.0.3:26379/7"
          files: ${{ github.event.inputs.files }}
          dirs: ${{ github.event.inputs.dirs }}
          depth: ${{ github.event.inputs.depth }}
          bytes: ${{ github.event.inputs.bytes }}
          threads: ${{ github.event.inputs.threads }}

  test-with-tikv:
    runs-on: [self-hosted, daily-build, bench-02]
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/mdtest
        with:
          meta_url: "tikv://172.27.0.1:2379,172.27.0.2:2379,172.27.0.3:2379/mdtest"
          files: ${{ github.event.inputs.files }}
          dirs: ${{ github.event.inputs.dirs }}
          depth: ${{ github.event.inputs.depth }}
          bytes: ${{ github.event.inputs.bytes }}
          threads: ${{ github.event.inputs.threads }}
